import React, { useEffect, useState } from "react";
import AppShell from "../components/AppShell";
import { api } from "../api";

export default function AlertsPage() {
  const eventOptions = ["down", "recovered", "anomaly", "ssl_expiring"];
  const [channels, setChannels] = useState([]); const [form, setForm] = useState({ type: "webhook", name: "", target_url: "", events: eventOptions }); const [message, setMessage] = useState("");
  async function load() { setChannels((await api.alertChannels()).channels || []); }
  useEffect(() => { load().catch((e) => setMessage(e.message)); }, []);
  async function add(e) { e.preventDefault(); try { await api.createAlertChannel(form); setForm({ type: "webhook", name: "", target_url: "", events: eventOptions }); setMessage("Channel added"); load(); } catch (e) { setMessage(e.message); } }
  async function updateChannel(channel, patch) { try { const response = await api.updateAlertChannel(channel.id, patch); setChannels((current) => current.map((item) => item.id === channel.id ? response.channel : item)); } catch (e) { setMessage(e.message); } }
  function toggleEvent(event) { setForm({ ...form, events: form.events.includes(event) ? form.events.filter((item) => item !== event) : [...form.events, event] }); }
  return <AppShell connected><h1 style={s.h1}>Alert channels</h1><p style={s.sub}>Send down, recovery, anomaly and SSL notifications.</p><form onSubmit={add} style={s.form}><select style={s.input} value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option>webhook</option><option>slack</option><option>discord</option></select><input required style={s.input} placeholder="Name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input required type="url" style={s.input} placeholder="Webhook URL" value={form.target_url} onChange={(e) => setForm({ ...form, target_url: e.target.value })} /><div style={s.events}>{eventOptions.map((event) => <label key={event}><input type="checkbox" checked={form.events.includes(event)} onChange={() => toggleEvent(event)} /> {event}</label>)}</div><button style={s.button}>Add</button></form>{message && <div style={s.message}>{message}</div>}<div style={s.list}>{channels.map((c) => <div style={s.row} key={c.id}><span><strong>{c.name}</strong><small>{c.type} · {c.target_url}</small></span><label style={s.enabled}><input type="checkbox" checked={c.enabled} onChange={(e) => updateChannel(c, { enabled: e.target.checked })} /> enabled</label><button style={s.small} onClick={() => api.testAlertChannel(c.id).then(() => setMessage("Test delivered")).catch((e) => setMessage(e.message))}>Send test</button><button style={s.danger} onClick={() => api.deleteAlertChannel(c.id).then(load)}>Delete</button></div>)}</div></AppShell>;
}
const s = { h1: { color: "#e2e8f0" }, sub: { color: "#718096" }, form: { display: "flex", gap: 8, flexWrap: "wrap", margin: "20px 0" }, input: { background: "#0f1117", color: "#e2e8f0", border: "1px solid #2d3748", borderRadius: 7, padding: 9 }, button: { background: "#4FD1C5", border: 0, borderRadius: 7, padding: "8px 14px" }, events: { display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center", color: "#a0aec0", fontSize: 12 }, list: { border: "1px solid #1e2535", borderRadius: 8 }, row: { display: "flex", alignItems: "center", gap: 12, padding: 14, borderBottom: "1px solid #1e2535" }, enabled: { color: "#a0aec0", fontSize: 12 }, small: { background: "#1e2535", color: "#c8d0e0", border: 0, padding: 7 }, danger: { color: "#fc8181", background: "transparent", border: 0 }, message: { color: "#68d391", marginBottom: 10 } };
